// ==UserScript==
// @name         Nihongo de ok for RES settings
// @namespace    nihongo-de-ok-for-res-settings
// @version      0.1.1
// @description  Reddit Enhancement Suite(RES)の設定画面を日本語に翻訳します
// @author       kusotool
// @include      http://www.reddit.com/*
// @include      https://www.reddit.com/*
// @grant        none
// @license      GNU General Public License version 3 or later
// ==/UserScript==
//
//	This program is free software: you can redistribute it and/or modify
//	it under the terms of the GNU General Public License as published by
//	the Free Software Foundation, either version 3 of the License, or
//	(at your option) any later version.
//
//	This program is distributed in the hope that it will be useful,
//	but WITHOUT ANY WARRANTY; without even the implied warranty of
//	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//	GNU General Public License for more details.
//
//	You should have received a copy of the GNU General Public License
//	along with this program.  If not, see <http://www.gnu.org/licenses/>.
//

var translated = false;
var t = [];  //translate data
var rt = [
    new regr(/Display expander for ([\w.]*)/, "$1の展開ボタンを表示する。"),
    new regr(/[Ss]how "([\w.]*)" link in subreddit manager/, "トップバーに[$1]を表示する。"),
    new regr(/Open link #(\d{1,2}) within comment./, "[$1]番目のリンクを開く。")
];

function E(id){
	return document.getElementById(id);
}

function regr(regex, replace){
    this.regex = regex;
    this.replace = replace;
}

function reg(arrayData){
    if(arrayData.length % 2 == 1){
        arrayData.push("");
    }

    while(arrayData.length > 0){
        var l = arrayData.shift();
        var r = arrayData.shift();
        if(!t[l] && t[l] !== ""){
            t[l] = r;
        }
    }
}

function GetActiveTab(){
    var e = document.getElementsByTagName("li");
    for(var i = 0; i < e.length; i++){
        if(/active/.test(e[i].getAttribute("class")) && /Menu-/.test(e[i].id)){
            return e[i].id;
        }
    }
    return null;
}

function GetActiveList(){
    var e = document.getElementsByTagName("div");
    for(var i = 0; i < e.length; i++){
        if(!(/activeE/.test(e[i].getAttribute("class"))) && /active/.test(e[i].getAttribute("class"))){
            return e[i].id;
        }
    }
    return null;
}

function TranslateRightPane(e){
    for(; e && e != "undefined"; e = e.nextSibling){
        if(e.getAttribute && e.getAttribute("moduleid") == "filteReddit"){
            e.addEventListener("click", function(){	TranslateRightPane(E("RESConfigPanelOptions"));	}, false);
        }
        if(typeof(t[e.nodeValue]) === "string"){
            e.nodeValue = t[e.nodeValue];
        }
        else{
            for(var i = 0; i < rt.length; i++){
                if(rt[i].regex.test(e.nodeValue)){
                    var s = "" + e.nodeValue;
                    e.nodeValue = s.replace(rt[i].regex, rt[i].replace);
                }
            }
        }
        if(e.hasChildNodes){
            if(e.getAttribute && e.getAttribute("for") === "subreddits"){
                //skip
            }
            else{
                TranslateRightPane(e.childNodes[0]);
            }
        }
    }
}

function TranslateLeftPane(id, strja){
	var e = E(id);
	e.innerHTML = e.innerHTML + "<br>" + strja;
	e.addEventListener("click", function(){	TranslateRightPane(E("RESConfigPanelOptions"));	}, false);
}

function TranslateTab(id, strja, arrayTranslateLeftPane){
	var e = E(id);
	e.innerHTML = strja;
	e.addEventListener("click", function(){
		for(var index = 0; index < arrayTranslateLeftPane.length; index += 2){	
			TranslateLeftPane(arrayTranslateLeftPane[index], arrayTranslateLeftPane[index+1]);
		}
		E(arrayTranslateLeftPane[0]).click();
	}, false);
}

function init(){
	reg([
        "Store username/password pairs and switch accounts instantly while browsing Reddit!",
        "ユーザー名(ID)とパスワードの組み合わせを複数保存しておき、アカウントをすぐに切り替えることができます。",
        "Keep me logged in when I restart my browser.",
        "ブラウザを再起動してもログイン状態を維持する。",
        "Set your usernames and passwords below. They are only stored in RES preferences.",
        "[+add account]ボタンを押してユーザー名とパスワードを登録してください。これらはRESの設定としてのみ保存されます。",
        "username",
        "ユーザー名",
        "password",
        "パスワード",
        "delete",
        "削除",
        "move",
        "移動",
        "Show my current user name in the Account Switcher.",
        "アカウント切り替え機能で選択中のユーザー名を表示する。",
        " snoo (alien) ",
        "snooアイコン",
        " simple arrow ",
        "シンプルな矢印",
        "Use the \"snoo\" icon, or older style dropdown?",
        "　ドロップダウンスタイルを選択する。",
        "Shows your comment karma next to your link karma.",
        "リンクカルマの隣にコメントカルマを表示します。",
        "Separator character between post/comment karma",
        "リンクカルマとコメントカルマの間に表示する区切り文字。",
        "Use commas for large karma numbers",
        "カルマが大きな値ならコンマ区切りで表示する。",
        "Hide the user bar (username, karma, preferences, etc.) in the top right corner. ",
        "ユーザーバー（ユーザー名、カルマ、設定などが表示されるバー）を折り畳めるようにします。",
        " Previously part of Style Tweaks",
        "",
        "Is the userbar visible?",
        "ユーザーバーを表示するかどうか。",
        " Visible ",
        " 表示する ",
        " Hidden ",
        " 隠す ",
        "Is the button to toggle the userbar visible? Only applies when the user bar is visible",
        "ユーザーバーを折り畳むためのボタンを表示するかどうか。userbarStateが「隠す」の場合はこの設定によらず表示されます。",
        "Username hider hides your username from displaying on your screen when you're logged in to reddit. 	This way, if someone looks over your shoulder at work, or if you take a screenshot, your reddit username is not shown. 	This only affects your screen. There is no way to post or comment on reddit without your post being linked to the account 	you made it from.",
        "redditにログインした際にユーザー名を隠す（ダミーの名前で表示する）ことができます。これにより誰かがあなたの後ろから画面をのぞき見てもユーザー名が分からなくなります。この設定はあなたの画面表示にのみ影響し、実際の投稿が匿名になるわけではありません。",
        "What to replace your username with. Default is ~anonymous~.",
        "ユーザー名を隠すためにダミーの名前（表示名）を設定する。初期設定は ~anonymous~",
        "Allows you to specify the display text for a specific account. (useful in conjunction with the Account Switcher!)",
        "アカウントごとに表示名を設定する。Account Switcher（アカウント切り替え機能）と組み合わせると便利。",
        "Hide all accounts listed in perAccountDisplayText, not just the logged-in user.",
        "perAccountDisplayTextで設定した全てのユーザーで名前を隠す。offの場合はログイン中のユーザーのみ名前を隠す。",
        "Hide all accounts listed in Account Switcher. ",
        "Account Switcher（アカウント切り替え機能）で登録した全てのユーザーで名前を隠す。",
        " 			If an username isn't already listed in perAccountDisplayText, then hide that username with the default displayText.",
        "個別に表示名を設定していないものについては、最初のdisplayTextで設定した表示名になります。",
        "Mousing over the text hiding your username reveals your real username.",
        "表示名にマウスオーバーした時にユーザー名を表示する。",
        "			This makes it easy to double check that you're commenting/posting from the correct account,			while still keeping your username hidden from prying eyes.",
        "誤爆防止などの目的で名前を確認しやすくなりますが、他人に見られないように注意しましょう。",
        "Saves the state of hidden comments across page views.",
        "ページを移動してもコメントの非表示状態を保持できます。（[-]ボタンを押して折り畳んだ状態を記憶しておく）",
        "There are no configurable options for this module.",
        "この機能に設定はありません。",
        "Provides a comment navigation tool to easily find comments by OP, mod, etc.",
        "OP（サブミッション作成者の投稿）やモデレーターなどを見つけやすくします。",
        "Display Comment Navigator by default",
        "コメントナビゲーターをデフォルトで表示する。",
        "Display Comment Navigator when a user is highlighted",
        "ユーザーが強調表示された時にコメントナビゲーターを表示する。",
        "Provides shortcuts for easier markdown.",
        "マークダウン（表やリストなどを書くための記法）を簡単にするためのボタンを表示できます。",
        "Show user autocomplete tool when typing in posts, comments and replies",
        "投稿・コメント・返信を書くときに、ユーザー(/u/username)の入力候補を表示する。",
        "Show subreddit autocomplete tool when typing in posts, comments and replies",
        "投稿・コメント・返信を書くときに、サブレディット(/r/subreddit)の入力候補を表示する。",
        "Show formatting tools (bold, italic, tables, etc.) to the edit form for posts, comments, and other snudown/markdown areas.",
        "整形ツール（太字・斜体・表など）のボタンを表示する。",
        "Use keyboard shortcuts to apply styles to selected text",
        "キーボードショートカットで選択したスタイルを整形できるようにする。",
        "Pressing Ctrl+Enter or Cmd+Enter will submit your comment/wiki edit.",
        "Ctrl+EnterかCmd+Enterでコメント/wikiの編集を送信する。",
        "Pressing Ctrl+Enter or Cmd+Enter will submit your post.",
        "Ctrl+EnterかCmd+Enterでサブミッションを投稿する。",
        "Shows your currently logged in username to avoid posting from the wrong account.",
        "ログイン中のユーザー名をコメントの入力ボックスの上に表示（Commenting As: ユーザー名）し、誤爆防止に役立てる。",
        'Put in bold the "Commenting As" part if you are using an alt account. The first account in the Account Switcher module is considered as your main account.',
        "サブアカウントを使用している場合、Commenting Asを太字で表示する。アカウント切り替え機能で一番上に登録したものがメインアカウントとなり、それ以外はサブアカウントとなります。",
        "When submitting, display the number of characters entered in the title and text fields and indicate when you go over the 300 character limit for titles.",
        "投稿時に入力済文字数と文字数制限を表示する。",
        "Add macro buttons to the edit form for posts, comments, and other snudown/markdown areas.",
        "投稿画面にマクロボタン（事前に登録した文を簡単入力できるボタン）を表示する。",
        "Add buttons to insert frequently used snippets of text.",
        "よく使う文をマクロとして登録できます。",
        "After selecting a macro from the dropdown list, do not hide the list.",
        "マクロを選択した後、リストを閉じないようにする。",
        "When using macro, replace placeholders in text via pop-up prompt.			",
        "マクロを使用するとき、プレースホルダー（{{hensuu}}のように適当な変数名を中括弧で括ったもの）をポップアップで入力したものに置き換える。",
        "Example macro text:",
        "プレースホルダーを使用したマクロの例：",
        "			The {{adj1}} {{adj2}} {{animal}} jumped over the lazy {{dog_color}} dog. The {{animal}} is so {{adj1}}!			",
        "すごい{{nanika}}を感じる。今までにない何か熱い{{nanika}}を。（中略）{{jama1}}や{{jama2}}は入るだろうけど、絶対に流されるなよ。",
        "Some placeholders are automatically filled in when you use the macro:",
        "いくつかのプレースホルダーは自動的に置き換えられます。",
        "The current subreddit, in the form /r/subreddit",
        "現在のサブレディット。/r/subredditの形になります。",
        "Your username, in the form /u/username",
        "あなたのユーザー名。/u/usernameの形になります。",
        'The username of the "original poster", in the form /u/username. On a post'+"'s comments page, this the person who made the post; on a PM / modmail, this is the person who started the conversation",
        "OP（投稿の場合はサブミッションを立てた人、プライベートメッセージの場合は会話を始めた人）を/r/usernameの形で表示します。",
        "The current page's URL, like http://www.reddit.com/r/Enhancement/comments/123abc/example_post",
        "現在のページのURL。http://www.reddit.com/r/Enhancement/comments/123abc/example_post のように表示されます。",
        "The username of person you're replying to, in the form /u/username. ",
        "あなたが返信しようとしている相手のユーザー名。/u/usernameの形になります。",
        "The text which is currently selected (highlighted)",
        "現在選択中のテキスト。",
        "The current date and time in your locale",
        "あなたの地域における日付と時刻。",
        "The current date in your locale",
        "あなたの地域における日付。",
        "The selected text, escaped for snudown/markdown. Useful for text emoji like ¯\\_(ツ)_/¯",
        "現在選択中のテキスト。snudown/markdown用のエスケープ（*などの機能を持つ文字をそのまま表示するように加工）するのでAAを使用する場合に便利です。",
        "Show the comment tools on the ban note textbox.",
        "ban noteの入力画面でコメントツールを表示する。",
        "Adds a link to the yellow infobar to view deeply linked comments in their full context.",
        "黄色い情報バー（リンク先が個別の投稿だった時、対象の背景が黄色くなる）にリンクを追加し、他のコメントを見られるようにします。",
        "Add a \"View the Full Context\" link when on a comment link",
        "\"View the Full Context\"（そのコメントを含むスレッドを全て表示する）リンクを追加する。",
        "Change the default context value on context link",
        "コンテキストリンクのデフォルト値を変更できます。（この値の分だけ親コメントをさかのぼって表示する）",
        "Allows you to hide all comments except for replies to the OP for easier reading.",
        "子コメント（他の人のコメントに返信したコメント）を全て非表示にできるようにします。",
        "Automatically hide all but parent comments, or provide a link to hide them all?",
        "親コメント以外を自動的に隠す。",
        "Provides a live preview of comments, as well as a two column editor for writing walls of text.",
        "コメントのプレビューおよび長文編集用の2カラムエディタを有効にする。",
        "Enable the 2 column editor.",
        "2カラムエディタを有効にする。（入力ボックスの右下にbig editorボタンが追加される）",
        "Apply a 'draft' style  background to the preview to differentiate it from the comment textarea.",
        "区別のためにコメントのプレビューの背景を薄い縞模様にする。",
        "Show preview for comments",
        "コメントを入力する時にプレビューを表示する。",
        "Show preview for posts",
        "サブミッションを投稿する時にプレビューを表示する。",
        "Show preview for wiki pages",
        "wikiを編集する時にプレビューを表示する。",
        "Show preview for editing subreddit settings",
        "サブレディットを設定する時にプレビューを表示する。",
        "Show preview for ban notes",
        "ban noteのプレビューを表示する。",
        "Show the markdown live preview directly in the sidebar when editing",
        "サイドバーを編集する時にプレビューを表示する。",
        "Shows how many new comments there are since your last visit.",
        "あなたが最後に訪れてからいくつのコメントが付いたかを表示します。（※redditの個人設定で言語をEnglish [en_us]に設定しないと表示されません）",
        "Clean out cached comment counts of pages you haven't visited in [x] days - enter a number here only!",
        "日間訪れなかった場合にコメント数の記憶をクリアする。",
        "Automatically remove thread subscriptions in [x] days (enter zero to keep subscriptions indefinitely) - enter a number here only!",
        "日間でサブミッションの購読を自動停止する。（0にすると無期限）",
        "Helps discourage brigading and helps you avoid getting banned, by warning against voting 		or commenting when following \"No Participation\" (np) links, and by providing options to prevent you from 			accidentally participating.			",
        "No Participation(NP)リンクをたどった場合に投票またはコメントに関する警告を出します。（大雑把に説明すると、redditでは組織票が禁止されているためreddit内の他の投稿を紹介する場合に投票禁止モードを使うことがあります。これがNPモードであり、www.reddit.comのかわりにnp.reddit.comにリンクすれば有効になります。）",
        "Find out more about \"No Participation\".",
        "No Participationについてはこちらを見てください。（未翻訳）",
        "Hide vote buttons. If you have already visited the page and voted, your prior votes will still be visible.",
        "投票ボタンを隠す。もしすでに投票済みの場合はそのまま表示されます。",
        "Disable commenting.",
        "コメントできなくする。",
        "Enable NP mode in subreddits where you're a subscriber",
        "購読済みの場合でもNPモードを有効にする。",
        "Remove np mode when leaving a No-Participation page",
        "No-Participationのページを離れた場合にNPモードを解除する。",
        "	You can save comments with RES: click the ",
        "RESを使ってコメントを保存することができます。コメントの下にある",
        " button below the comment. You can view 	these comments on your user page under the \"saved - RES\" tab (reddit.com/user/MyUsername/saved#comments). 	If you use ",
        "ボタンをクリックすると保存され、\"saved - RES\"タブ(reddit.com/user/MyUsername/saved#comments)で見ることができます。",
        ", you can press . 	to open the RES command line, then type in ",
        "（キーボードで操作）が有効であれば場合は . （ドット）を押してコマンドラインを出した後 ",
        " to see saved-RES comments. 	",
        " と入力することでアクセスできます。",
        "	Saving with RES saves a comment locally in your browser. This means that you can see the comment you saved 	",
        "RESを使って保存したコメントはブラウザに保存されるので保存時の環境（同じPC、同じブラウザ、RESがインストール済）でなければ読めません。",
        "as it looked when you saved it",
        "",
        ", even if it is later edited or deleted. 	You can save comments with RES if you are not logged in, or if you are logged in to any account—all the 	comments will be visible in one location. You will only be able to view saved RES comments on whichever browser	you have RES istalled on.	",
        "しかしコメントが編集されたり削除されてもその内容は変わらないし、redditにログインしていなくても保存したり読んだりできます。",
        "		When saving comments with reddit, you must be logged into an account; the comment is saved specifically for that account;	it won't be shown if you switch to a different account or log out. You can view these comments whenever you are logged into	the reddit account you saved them from, including on other browsers or devices.  	",
        "redditの機能でコメントを保存するにはログインしておく必要があります。サーバー側に保存されるので他のデバイスやブラウザでもコメントを保存したユーザーでログインすれば読むことができます。コメントが編集されたり削除された場合は、保存したコメントもその影響を受けます。（コメントの内容ではなく、リンクを保存していると考えてください）",
        "		Visually, saving comments with reddit looks the same as saving with RES—but the text is not saved locally,	so the saved comment text shows the ",
        "",
        "current",
        "",
        " state of the comment. If the comment has been edited or deleted 	since you saved it, the text that displays on your account's \"saved\" page will look different then it looked when you saved it.	",
        "",
        "		If you have ",
        "",
        " on an account, you can add a category/tag to comments you have saved 	with reddit, then filter saved comments/posts by category. (You cannot sort or filter comments saved with RES.) 	",
        "アカウントを持っている場合は、そのアカウントで保存したコメントにカテゴリ・タグを追加することができ、それを利用してフィルタすることができます。（RESを使って保存したコメントではできません）",
        "Shows the parent comments when hovering over the \"parent\" link of a comment.",
        "parentリンクにマウスオーバーした時に親コメントを表示する。",
        "Delay, in milliseconds, before parent hover loads. Default is 500.",
        "ミリ秒　マウスオーバーしてからポップアップするまでの待機時間。（デフォルト値は500）",
        "Delay, in milliseconds, before parent hover fades away after the mouse leaves. Default is 200.",
        "ミリ秒　マウスカーソルが離れてからポップアップが消えるまでの待機時間。（デフォルト値は200）",
        "Fade animation's speed. Default is 0.3, the range is 0-1. Setting the speed to 1 will disable the animation.",
        "半透明処理の速度（0～1）を設定。1なら瞬時に表示する。（デフォルト値は0.3）",
        " Above ",
        " 上 ",
        " Below ",
        " 下 ",
        "Order the parent comments to place each parent comment above or below its children.",
        "親コメントを子コメントのどちら側に表示するかを決める。",
        "When changing the \"sort by\" for a post's comments, offer options to only do so temporarily.",
        "コメントをソートする時、右側の(temporarily?)をクリックすると一時的なソートを行えるようにする。",
        "Always change \"sort by\" temporarily; don't show the button",
        "コメントをソートする時、常に一時的なソートを行う。(temporarily?)は表示しない。",
        "Add tool to show the original text on posts and comments, before reddit formats the text.",
        "各投稿とコメントの下に書き込み時のソースコードを表示するためのsourceリンクを追加します。",
        "Filter out NSFW content, or links by keyword, domain (use User Tagger to ignore by user) or subreddit (for /r/all or /domain/*).",
        "NSFW（仕事場で見ない方が良いエロなど）コンテンツや、設定したキーワード、ドメイン、サブレディットをフィルタします。",
        "Filters all links labelled NSFW",
        "NSFWをフィルタします。",
        "If more than this percentage (0-100) of a page is filtered, show a notification",
        "パーセントを超える内容が1ページの中でフィルタ対象になった場合は通知を表示する。",
        "Add a quick NSFW on/off toggle to the gear menu",
        "歯車メニューにNSFWフィルタ切り替えボタンを表示する。",
        "When visiting the comments page for a filtered link, allow the link/expando to be shown",
        "フィルタしたリンクのコメントページでは、リンクの表示を許可する。",
        "Don't filter anything on modqueue pages (modqueue, reports, spam)",
        "modqueueページ（モデレーター用の違反報告、スパム報告の確認ページ）ではフィルタを行わない。",
        "Don't filter anything on users' profile pages",
        "ユーザープロフィールページではフィルタを行わない。",
        "Allow RegExp in certain filteReddit fields.",
        "Redditフィルタ（このページ）のいくつかの入力で正規表現を有効にする。",
        "If you have filters which start with ",
        "",
        ", you should turn this option off.",
        "（スラッシュ）で始まるフィルタを入力する場合にはoffにしてください。",
        "Type in title keywords you want to ignore if they show up in a title.\n\nRegExp like ",
        "タイトルで無視したいキーワードを入力してください。キーワードには ",
        " is allowed for keyword (but not unlessKeyword).",
        " のような正規表現が使えます。（除外キーワードでは使えません）",
        "keyword",
        "キーワード",
        "applyTo",
        "有効範囲",
        "subreddits",
        "サブレディット",
        "unlessKeyword",
        "除外キーワード",
        " Everywhere ",
        "全ての場所",
        " Everywhere but: ",
        "指定した場所以外",
        " Only on: ",
        "指定した場所",
        "Type in a subreddit you want to ignore (only applies to /r/all or /domain/* urls).\n\nRegExp like ",
        "無視したいサブレディットを入力してください（/r/all または /domain/* 形式のみ有効）。サブレディットには ",
        " is allowed for subreddit.",
        " のような正規表現が使えます。",
        "subreddit",
        "サブレディット",
        "Type in domain keywords you want to ignore. Note that \"reddit\" would ignore \"reddit.com\" and \"fooredditbar.com\"\n\nRegExp like ",
        "無視したいドメインを入力してください。redditと入力した場合、reddit.comやfooredditbar.comが無視される（部分一致で判定）ことに注意。ドメインには ",
        " is allowed for domain.",
        " のような正規表現が使えます。",
        "domain",
        "ドメイン",
        "Type in keywords you want to ignore if they are contained in link flair\n\nRegExp like ",
        "無視したいフレアーを入力してください。",
        " is allowed for flair.",
        " のような正規表現が使えます。",
        "Whitelist subreddits from NSFW filter",
        "NSFWフィルタのホワイトリストを指定してください。",
        "where",
        "どこで",
        " When browsing subreddit/multi-subreddit ",
        "サブレディットまたはマルチレディットを見るとき",
        "Adds a Spam button to posts for easy reporting.",
        "違反報告を簡単にするためにspamボタン（rtsと表示）を追加します。各書き込みの下側のflairまたはgive goldの右隣に表示されます。",
        "Adds tags to posts based on which subreddit they were posted to.",
        "投稿されたサブレディットを元にタグを追加します。",
        "Set your subreddit-specific tags below. You can avoid double tagging a post that has already been tagged by using the \"doesntContain\" field. So, if you want to make sure that all ",
        "サブレディットごとのタグを設定してください。タグが二重に付いてしまわないように含まない文字列を設定する必要があります。もし",
        " posts are tagged [TOMT], even if the user has forgotten, then put \"tipofmytongue\" as the subreddit, \"TOMT\" in the \"doesntContain\" field, and \"[TOMT]\" in the tag field. Subreddit tagger looks for the \"doesntContain\" text in the post's title and flair",
        "というサブレディットの投稿に[TOMT]というタグを付けたいのなら、サブレディットにtipsofmytongue、タグに[TOMT]、含まない文字列にTOMTを設定してください。含まない文字列は投稿のタイトルとフレアーを確認対象とします。",
        "doesntContain",
        "含まない文字列",
        "tag",
        "タグ",
        "Adds a number of interface enhancements to Reddit, such as \"full comments\" links, the ability to unhide accidentally hidden posts, and more",
        "いくつかの操作性向上を行います。間違って隠してしまった全ての投稿を元に戻すなどの機能があります。",
        "Add \"full comments\" link to comment replies, etc.",
        "コメントの返信などに\"full comments\"リンクを追加する。",
        "Text of full comments link.",
        "full commentsリンクを何と表示するか。",
        "Open links found in comments in a new tab.",
        "コメント中のリンクを新しいタブで開く。",
        "Changes \"hide\" links to read as \"hide\" or \"unhide\" depending on the hide state. Also adds a 5 second delay prior to hiding the link.",
        "表示状態によってhide/unhideが（隠す/隠すのをやめる）切り替わるようにします。また、表示を消す前に5秒間の猶予を追加します。",
        "Show unread message count next to orangered? If set to false, this will hides reddit's new native functionality once that is added.",
        "メッセージアイコンの隣に未読メッセージ数を表示する。",
        "If you dislike the unread count provided by native reddit, you can replace it with the RES-style bracketed unread count",
        "未読数表示をreddit標準ではなくRESスタイルにする。",
        "Show unread message count in page/tab title?",
        "未読メッセージ数をページ/タブのタイトルに表示する。",
        "Show unread message count in favicon?",
        "未読メッセージ数をアイコンに表示する。",
        "Always go to the inbox, not unread messages, when clicking on orangered",
        "未読メッセージ通知をクリックした場合、未読メッセージ一覧ではなくメッセージ受信箱に移動する。",
        "Uncheck \"send replies to my inbox\" by default, when submitting a new post",
        "投稿する時に返信通知をデフォルトでoffにする。",
        "Hide the mod mail button in user bar.",
        "ユーザーバーからモデレーターにメールするボタンを隠す。",
        "Show lengths of videos when possible",
        "ビデオの長さが分かる場合は表示する。",
        "Show upload date of videos when possible",
        "ビデオのアップロード日が分かる場合は表示する。",
        "Show number of views for a video when possible",
        "ビデオの再生数が分かる場合は表示する。",
        "Don't use Reddit Toolbar when linking to sites that may not function (twitter, youtube and others)",
        "レディットツールバーが使えない可能性があるサイトにリンクしている時は使わない。",
        " None ",
        " なし ",
        " Subreddit Bar only ",
        " トップバーだけ ",
        " User Bar ",
        " ユーザーバー ",
        " Subreddit Bar and User bar ",
        " トップバーとユーザーバー ",
        " Full Header ",
        " ヘッダー全体 ",
        "Pin the subreddit bar or header to the top, even when you scroll.",
        "　スクロール時にトップバーまたはヘッダーを固定する。",
        "Show the time that a text post/comment was edited, without having to hover the timestamp.",
        "タイムスタンプにマウスオーバーしなくても投稿やコメントの編集時刻を表示する。",
        "When hovering [score hidden] show time left instead of hide duration.",
        "[score hidden]にマウスオーバーした時、非表示の時間ではなく残り時間を表示する。",
        "The saved tab is now located in the multireddit sidebar. This will restore a \"saved\" link to the header (next to the \"hot\", \"new\", etc. tabs).",
        "savedタブ（マルチレディット・フロントページのサイドバーにある）をヘッダー（\"hot\"や\"new\"のある列）に表示する。",
        "Opens images inline in your browser with the click of a button. Also has configuration options, check it out!",
        "投稿やコメントに画像URLがあった場合、ページを移動せずに画像を展開できるようにします。",
        "Conserve memory by temporarily hiding images when they are offscreen.",
        "表示領域から外れた画像を非表示にしてメモリーを節約する。",
        "Preload gallery images for faster browsing. Beware: this is at the expense of lots of bandwidth usage.",
        "画像の先読みを行うことで表示の高速化を行う。注意：この機能は通信量を増大させます。",
        "Hide images that are further than x screens away to save memory. A higher value means less flicker, but less memory savings.",
        "指定した画面分離れた画像を隠す。大きくするほど再表示が遅れにくくなりますが、メモリー節約効果も低下します。",
        "Max width of image displayed onscreen",
        "画像を表示する時の最大の幅。",
        "Max height of image displayed onscreen",
        "画像を表示する時の最大の高さ。",
        "Display each image's original (unresized) resolution in a tooltip.",
        "画像のオリジナル解像度をツールチップ（マウスオーバー時に出る）で表示する。",
        "Add a scroll bar to text expandos taller than [x] pixels (enter zero for unlimited).",
        "クリックして展開するテキストが指定した高さ（単位：ピクセル）よりも長い場合はスクロールバーを表示する。（0の場合はスクロールバーを表示しない）",
        "Add a scroll bar to comments taller than [x] pixels (enter zero for unlimited).",
        "指定した高さ（単位：ピクセル）よりも長いコメントならスクロールバーを表示する。（0の場合はスクロールバーを表示しない）",
        "Increase the max height of a self-text expando or comment if an expando is taller than the current max height.				This only takes effect if max height is specified (previous two options).",
        "展開するテキストまたはコメントが長い場合は高さを伸ばす。（上の二つの設定が有効な場合のみ）",
        "Open images in a new tab/window when clicked?",
        "画像クリックしたとき新しいタブまたはウィンドウで開く。",
        "If checked, do not show images marked NSFW.",
        "NSFW（仕事場で見ない方が良いエロなど）とマークされた画像を開かない。",
        "When loading selftext from an Aa+ expando, auto expand images, videos, and embeds.",
        "[Aa+]ボタンを押してテキストを展開する時、画像やビデオも展開する。",
        "Allow dragging to resize/zoom images.",
        "マウスドラッグで画像をリサイズできるようにする。",
        "Allow dragging while holding shift to move images.",
        "シフトキーを押しながらマウスドラッグで画像を移動できるようにする。",
        "Show educational tooltips, such as showing \"drag to resize\" when your mouse hovers over an image.",
        "画像にマウスオーバーした時にdrag to resize（ドラッグしてリサイズできます）などの表示をする。（残念ながらその時の表示は日本語化されません）",
        "Mark links visited when you view images (does eat some resources).",
        "画像を見たとき、それをすでに見た画像としてマークする。（いくらかのリソースを消費します）",
        " Add links to history ",
        " リンクを履歴に残す ",
        " Color links, but do not add to history ",
        " リンクに色は付けるが履歴には残さない ",
        " Do not add or color links. ",
        " リンクに色を付けず履歴にも残さない ",
        "Keeps NSFW links from being added to your browser history ",
        "　NSFWなリンクをmarkVisited機能によりブラウザの履歴に残すか選びます。",
        "by the markVisited feature",
        "",
        "If you chose the second option, then links will be blue again on refresh.",
        "　二番目のオプションを選んだ場合、再読み込みで元の色に戻ります。",
        "This does not change your basic browser behavior.				If you click on a link then it will still be added to your history normally.				This is not a substitute for using your browser's privacy mode.",
        "　この機能はブラウザの基本機能を変更するわけではなく、リンクをクリックすると履歴に残ります。この機能はブラウザのプライバシーモードの代わりにはなりません。",
        "Do not create expandos for images that appear multiple times in a page.",
        "1ページ中に同じ画像が複数回出てきた場合は展開ボタンを作らない。",
        "Retrieve image captions/attribution information.",
        "画像のタイトルや属性情報を取得する。",
        "Display all images at once in a 'filmstrip' layout, rather than the default navigable 'slideshow' style.",
        "全ての画像をデフォルトのスライドショースタイルではなくフィルムストリップ レイアウトで表示する。",
        "Use the 'slideshow' style for albums with more images than this number. (0 for always use 'filmstrip')",
        "以上の画像を含むアルバムはスライドショースタイルで表示する。（0の場合、常にフィルムストリップ）",
        "Convert Gif links to Gfycat links.",
        "GIF画像へのリンクをGfycatへのリンクに変換する。",
        "Show a 'view images' tab at the top of each subreddit, to easily toggle showing all images at once.",
        "view imagesタブを各サブレディットのトップに表示する。これにより全ての画像を一気に開閉できます。",
        "Autoplay inline videos",
        "インラインビデオを自動再生する。",
        "Prefer RES support for imgur albums rather than reddit's built in support",
        "redditの標準機能の代わりにRESによるimgurアルバム機能を使う。",
        "Show a toggle for radd.it embeds in subreddits with sidebar links to a raddit.com/r/subreddit playlist",
        "サブレディットのサイドバーリンクに埋め込まれたradd.itのリンクをraddit.com/r/subredditプレイリストに置き換えるボタンを表示する。",
        "Start playing the radd.it sidebar embed when opening it",
        "埋め込まれたradd.itサイドバーを開いたときに再生を始める。",
        "Always show the radd.it embed in the sidebar when applicable",
        "可能なら常にradd.itの埋め込みを表示する。",
        "Keyboard navigation for reddit!",
        "キーボードでredditを操作できます！",
        "Set a background color to highlight the currently focused element",
        "選択中の項目を強調するために背景色を設定する。",
        "Background color of focused element",
        "選択中の項目の背景色。",
        "Background color of focused element in Night Mode",
        "ナイトモード時の選択中の項目の背景色。",
        "Foreground color of focused element in Night Mode",
        "ナイトモード時の選択中の項目の色。",
        "Set a border to highlight the currently focused element",
        "選択中の項目を強調するためにボーダーを設定する。",
        "border style (e.g. 1px dashed gray) for focused element",
        "選択中の項目のボーダースタイル。（例：1px dashed gray）",
        "border style (e.g. 1px dashed gray) for focused element in Night Mode",
        "ナイトモード時の選択中の項目のボーダースタイル。（例：1px dashed gray）",
        "Automatically select the topmost element for keyboard navigation on window scroll",
        "キーボード操作時、ウィンドウがスクロールしたら自動的に一番上の項目を選択する。",
        "If media is open on the currently selected post when moving up/down one post, open media on the next post.",
        "現在選択中の投稿のメディアを開いている場合は、上/下に移動したときにメディアを開く。",
        "Scroll window to top of link when expando key is used (to keep pics etc in view)",
        "展開キーを押した時、ウィンドウをスクロールする。（画像が画面におさまるようにするため）",
        " directional ",
        " 最下行に達した時、一行スクロール ",
        " page up/down ",
        " 最下行に達した時、一ページスクロール ",
        " lock to top ",
        " 選択行が常に一番上になるようにスクロール ",
        "When moving up/down with keynav, when and how should RES scroll the window?",
        "　キーボードで上/下に移動する時、いつどのようにウィンドウをスクロールしますか？（上に移動するときはページ単位のスクロールにはなりません）",
        "Assign number keys (e.g. [1]) to links within selected comment",
        "選択したコメント中のリンクに数字キーを割り当てる。（対応する数字キーを押すと、そのリンクを開けます）",
        " Place on right ",
        " 右側 ",
        " Place on left ",
        " 左側 ",
        "Which side commentsLinkNumbers are displayed",
        "commentsLinkNumbersで割り当てた数字キーをどちらに表示するか選びます。",
        "Open number key links in a new tab",
        "数字キーでリンクを開くとき、新しいタブで開きます。",
        "Move keyboard focus to a link or comment when clicked with the mouse",
        "マウスでクリックしたリンクやコメントにキーボードフォーカス（選択状態）を移動します。",
        "After hiding a link, automatically select the next link",
        "リンクを非表示にした後、次のリンクを自動的に選択する。",
        "After voting on a link, automatically select the next link",
        "リンクに投票したら、自動で次のリンクを選択する。",
        "After voting on a comment, automatically select the next comment",
        "コメントに投票したら、自動で次のコメントを選択する。",
        "Show help for keyboard shortcuts",
        "キーボードショートカットのヘルプを表示するキーを指定します。",
        "Use go mode (require go mode before \"go to\" shortcuts are used, e.g. frontpage)",
        "goモードを使用する。（goモードに入らないと[goモード対応]の移動操作ができないようにする/offなら直接移動可）",
        "Enter \"go mode\" (next keypress goes to a location, e.g. frontpage)",
        "goモードに入る。",
        "Show/hide commandline box",
        "コマンドラインボックスを開閉する。",
        "Hide link",
        "リンクを隠す。",
        "Move up (previous link or comment)",
        "上に移動する。（前のリンクまたはコメント）",
        "Move down (next link or comment)",
        "下に移動する。（次のリンクまたはコメント）",
        "Move to top of list (on link pages)",
        "リストの先頭に移動する。（リンクページ専用）",
        "Move to bottom of list (on link pages)",
        "リストの最後に移動する。（リンクページ専用）",
        "Move to previous sibling (in comments) - skips to previous sibling at the same depth.",
        "前の兄弟コメントに移動する。同じ深さの前の兄弟までスキップします。",
        "Move to next sibling (in comments) - skips to next sibling at the same depth.",
        "次の兄弟コメントに移動する。同じ深さの次の兄弟までスキップします。",
        "Move to the topmost comment of the previous thread (in comments).",
        "前のスレッドの先頭のコメントに移動する。",
        "Move to the topmost comment of the next thread (in comments).",
        "次のスレッドの先頭のコメントに移動する。",
        "Move to the topmost comment of the current thread (in comments).",
        "現在のスレッドの先頭のコメントに移動する。",
        "Move to parent (in comments).",
        "親コメントに移動。",
        "Display parent comments.",
        "親コメントをポップアップ表示。",
        "Follow link (hold shift to open it in a new tab) (link pages only)",
        "リンクを開く。（シフトキーを押しながらだと新しいタブで開く）（リンクページのみ）",
        "Follow link in new tab (link pages only)",
        "リンクを新しいタブで開く。（リンクページのみ）",
        "When following a link in new tab - focus the tab?",
        "リンクを新しいタブで開くとき、そのタブをフォーカスする？",
        "Toggle expando (image/text/video) (link pages only)",
        "画像/テキスト/ビデオを展開する。（リンクページのみ）",
        "Increase the size of image(s) in the highlighted post area",
        "選択した投稿エリアの画像を大きくする。",
        "Decrease the size of image(s) in the highlighted post area",
        "選択した投稿エリアの画像を小さくする。",
        "Increase the size of image(s) in the highlighted post area (finer control)",
        "選択した投稿エリアの画像を大きくする。（より細かく調整できる）",
        "Decrease the size of image(s) in the highlighted post area (finer control)",
        "選択した投稿エリアの画像を小さくする。（より細かく調整できる）",
        "Move the image(s) in the highlighted post area up",
        "選択した投稿エリアの画像を上に移動する。",
        "Move the image(s) in the highlighted post area down",
        "選択した投稿エリアの画像を下に移動する。",
        "Move the image(s) in the highlighted post area left",
        "選択した投稿エリアの画像を左に移動する。",
        "Move the image(s) in the highlighted post area right",
        "選択した投稿エリアの画像を右に移動する。",
        "View the previous image of an inline gallery.",
        "インラインギャラリーの前のイメージを見る。（\"← 01 of 20 →\"のような表示がある場合の画像切り替えを行う）",
        "View the next image of an inline gallery.",
        "インラインギャラリーの次のイメージを見る。（\"← 01 of 20 →\"のような表示がある場合の画像切り替えを行う）",
        "Toggle \"view images\" button",
        "\"view images\"ボタン（ページ内の全ての画像を開閉）を押す。",
        "Expand/collapse comments (comments pages only)",
        "コメントの展開と折り畳み。（コメントページのみ）",
        "View comments for link (shift opens them in a new tab)",
        "コメントページを開く。（シフトを押しながらだと新しいタブで開く）",
        "View comments for link in a new tab",
        "コメントページを新しいタブで開く。",
        "View link and comments in new tabs",
        "リンクとコメントを新しいタブで開く。",
        "View link and comments in new background tabs",
        "リンクとコメントを新しいバックグラウンドタブで開く。",
        "Upvote selected link or comment (or remove the upvote)",
        "リンクまたはコメントにUpvoteする。（または取り消す）",
        "Downvote selected link or comment (or remove the downvote)",
        "リンクまたはコメントにDownvoteする。（または取り消す）",
        "Upvote selected link or comment (but don't remove the upvote)",
        "リンクまたはコメントにUpvoteする。（取り消しはしない）",
        "Downvote selected link or comment (but don't remove the downvote)",
        "リンクまたはコメントにDownvoteする。（取り消しはしない）",
        "Save the current post to your reddit account. This is accessible from anywhere that you're logged in, but does not preserve the original text if it's edited or deleted.",
        "投稿をredditアカウントに保存する。ログインすればどこからでもアクセスできますが、編集や削除によって影響を受けます。（投稿の内容ではなくアドレスを保存していると考えてください）",
        "Save the current comment to your reddit account. This is accessible from anywhere that you're logged in, but does not preserve the original text if it's edited or deleted.",
        "コメントをredditアカウントに保存する。ログインすればどこからでもアクセスできますが、編集や削除によって影響を受けます。（投稿の内容ではなくアドレスを保存していると考えてください）",
        "Save the current comment with RES. This does preserve the original text of the comment, but is only saved locally.",
        "投稿をRESに保存する。保存後にそのコメントが編集されても内容が維持されますが、保存したPCからしか見ることができません。",
        "Reply to current comment (comment pages only)",
        "コメントに返信する。（コメントページのみ）",
        "Open the current comment's permalink (comment pages only)",
        "コメントのパーマリンク（そのコメントだけ表示するリンク）を開く。（コメントページのみ）",
        "Open the current comment's permalink in a new tab (comment pages only)",
        "コメントのパーマリンクを新しいタブで開く。（コメントページのみ）",
        "Open the current markdown field in the big editor. (Only when a markdown form is focused)",
        "big editorを開く。（コメント編集中のみ）",
        "Go to subreddit of selected link (link pages only)",
        "選択したリンクが投稿されているサブレディットを開く。（リンクページをマルチレディットで表示している時などに有効）",
        "Go to subreddit of selected link in a new tab (link pages only)",
        "選択したリンクが投稿されているサブレディットを新しいタブで開く。（リンクページをマルチレディットで表示している時などに有効）",
        "Go to inbox",
        "[goモード対応] メッセージの受信箱を開く。",
        "Go to inbox in a new tab",
        "[goモード対応] メッセージの受信箱を新しいタブで開く。",
        "Go to modmail",
        "[goモード対応] modmailを開く。",
        "Go to modmail in a new tab",
        "[goモード対応] modmailを新しいタブで開く。",
        "Go to profile",
        "[goモード対応] プロフィールを開く。",
        "Go to profile in a new tab",
        "[goモード対応] プロフィールを新しいタブで開く。",
        "Go to front page",
        "[goモード対応] フロントページを開く。",
        "Go to subreddit front page",
        "[goモード対応] サブレディットのフロントページを開く。",
        "Go to a random subreddit",
        "[goモード対応] ランダムなサブレディットに行く。",
        "Go to next page (link list pages only)",
        "[goモード対応] 次のページに行く。（リンク一覧ページでのみ有効）",
        "Go to prev page (link list pages only)",
        "[goモード対応] 前のページに行く。（リンク一覧ページでのみ有効）",
        "Open Comment Navigator",
        "コメントナビゲーターを開く。",
        "Move up using Comment Navigator",
        "コメントナビゲーターを使用して上に移動する。",
        "Move down using Comment Navigator",
        "コメントナビゲーターを使用して下に移動する。",
        "Shows date in your local time zone when you hover over a relative date.",
        "1 days agoなどの表示にマウスオーバーした時に日付と時刻を表示する。",
        "Allow you to change the link on the reddit logo.",
        "redditロゴ（snoo）をクリックしたときの移動先を設定できます。",
        " Frontpage ",
        "フロントページ",
        " Current subreddit/multireddit ",
        "現在のサブレディット/マルチレディット",
        "Location when you click on the reddit logo.",
        "redditロゴ（snoo）をクリックしたときの移動先を設定してください。",
        "Inspired by modules like River of Reddit and Auto Pager - gives you a never ending stream of reddit goodness.",
        "次のページを自動的に読み込んで連結させる機能です。下にスクロールしていくだけでどんどん読むことができます。",
        "Return to the page you were last on when hitting \"back\" button?",
        "ブラウザの戻るボタンを押した時、最後に見ていたページに戻る。",
        "Automatically load new page on scroll (if off, you click to load)",
        "自動的に次のページを読み込む。（offの場合はクリックして読み込みます）",
        "Show a reminder to unpause Never-Ending Reddit after pausing",
        "Never Ending Reddit機能を一時停止した時、一時停止の解除を忘れないように通知する。",
        "Show \"paused\" bars icon when auto-load is paused and \"play\" wedge icon when active",
        "自動読み込みを中止している間は一時停止のアイコンを表示する。（onでは自動読み込み機能の「状態」を表示し、offでは「押した場合の変化」を表示します）",
        "Show the π server / debug details next to the floating Never-Ending Reddit tools",
        "πサーバーを表示する。（マウスオーバーでデバッグ情報表示）",
        "After auto-loading a certain number of pages, pause the auto-loader",
        "指定したページ数を読み込んだら自動読み込みを一時停止する。",
        "0 or a negative number means Never-Ending Reddit will only pause when you click the play/pause button in the top right corner.",
        "0またはマイナス値の場合、読み込みページ数による一時停止をしません。",
        "Fade or completely hide duplicate posts from previous pages.",
        "次のページを連結する前に新しい投稿があった場合などに発生するダブりの扱い。",
        " Fade ",
        " 半透明にする ",
        " Hide ",
        " 隠す ",
        " Do not hide ",
        " 隠さない ",
        "A darker, more eye-friendly version of Reddit suited for night browsing.		",
        "明るさを抑え、夜の閲覧用に目に優しい表示にします。",
        "Note: Using this on/off switch will disable all features of the night mode module completely.		",
        "注意：ここで機能を無効にするとナイトモードの全ての機能が無効になります。",
        "To simply turn off night mode, use the nightModeOn switch below.",
        "単に今はナイトモードを無効にしておきたいだけ（ナイトモードを後で使うつもりがある）なら下のnightModeOnスイッチを使用してください。",
        "Enable/disable night mode.",
        "ナイトモードのon/offを切り替える。",
        "Enable night switch, a toggle between day and night reddit located in the Settings dropdown menu.",
        "歯車メニュー内にナイトモードの切り替えスイッチを表示する。",
        "Enable automatic night mode—night mode automatically starts and stops at the times configured below.				",
        "時刻に応じて自動的にナイトモードに切り替える。",
        "For the times below, a 24-hour clock (\"military time\") from 0:00 to 23:59 is used.				",
        "",
        "e.g. the time 8:20pm would be written as 20:20, and 12:30am would be written as 00:30 or 0:30.				",
        "",
        "To temporarily override automatic night mode, manually flip the night mode switch.				",
        "",
        "Configure how long the override lasts below.",
        "",
        "Time that automatic night mode starts. Default is 20:00 (8:00pm).",
        "ナイトモードを開始する時刻を設定する。デフォルトは20：00です。",
        "Time that automatic night mode ends. Default is 6:00 (6:00am).",
        "ナイトモードを終了する時刻を設定する。デフォルトは6：00です。",
        "Number of hours that the automatic night mode override lasts. Default is 8 (hours).				",
        "ナイトモードを上書きする時間（ナイトモード中に手動でoffにした場合、何時間後にonに戻すか）を設定する。デフォルトは8時間で、例えば0.1を設定すると6分となります。",
        "You can use a decimal number of hours here as well; e.g. 0.1 hours (which is 6 min).",
        "",
        "Don't disable subreddit styles by default when using night mode.				",
        "ナイトモード時にサブレディットのスタイル(CSS)を無効化しないようにする。",
        "When using night mode, subreddit styles are automatically disabled unless ",
        "通常はナイトモード時にナイトモード非対応のサブレディットのスタイルは無効になります。",
        "the subreddit indicates it is night mode-friendly",
        "",
        ". You must tick the \"Use subreddit stylesheet\" in a subreddit's sidebar to enable subreddit styles in that subreddit. This is because most subreddits are not night mode-friendly.				",
        "",
        "If you choose to show subreddit styles, you will see flair images and spoiler tags, but be warned: ",
        "この機能を有効にすれば、ナイトモード時にナイトモード非対応のサブレディットのスタイルで表示することができますが、ナイトモードにふさわしくない明るい表示になることがあります。",
        "you may see bright images, comment highlighting, etc.",
        "",
        " It is up to the mods of each subreddit to make their sub night mode friendly, which is not a tiny amount of work. Please be polite when requesting moderators make a sub night mode friendly.",
        "根本的な解決にはモデレーターにナイトモード対応のスタイルを作成してもらう必要がありますが、それにかかる労力は小さくありません。モデレーターに無理な注文を付けないようにしてください。",
        "Allow the subreddits listed to display subreddit styles during night mode if useSubredditStyles is disabled.",
        "ここに指定したサブレディットではナイトモード時のサブレディットのスタイル使用を許可する。（useSubredditStylesはoffにしてください）",
        "A pop-up dialog that allows you to send messages from anywhere on reddit.		Messages can be sent from the quick message dialog by pressing control-enter or command-enter.",
        "redditのどこにいてもメッセージを送信できるポップアップダイアログを出す機能です。クイックメッセージダイアログでCtrl+EnterかCommand+Enterキーを押すとメッセージを送信します。",
        "Keyboard shortcut to open the quick message dialog.",
        "クイックメッセージ入力ボックスを開くキーボードショートカットを指定する。",
        "Text that will automatically be inserted into the subject field, unless it is auto-filled by context.",
        "ここに入力したテキストをデフォルトの題名にする。入力しない場合は文脈により自動的に埋められます。",
        "Open the quick message dialog when clicking on \"message the moderators\" instead of going straight to reddit's message page.",
        "\"message the moderators\"をクリックしたとき、redditのメッセージページに移動せずにクイックメッセージ入力ボックスを開く。",
        "The RES Dashboard is home to a number of features including widgets and other useful tools",
        "RESダッシュボードではウィジットやその他の便利な機能を使えます。",
        "Number of posts to show by default in each widget",
        "各ウィジットで表示するデフォルトの投稿数。",
        " hot ",
        " hot（注目） ",
        " new ",
        " new（新着） ",
        " rising ",
        " rising（上昇中） ",
        " controversial ",
        " controversial（論争中） ",
        " top ",
        " top（トップ） ",
        "Default sort method for new widgets",
        "新しいウィジットのデフォルトのソート方法。",
        "Show +dashboard shortcut in sidebar for easy addition of dashboard widgets.",
        "ダッシュボードウィジットへの登録が簡単にできるように、サイドバーに [+dashboard] ボタンを表示する。",
        "How many user tags to show per page on the ",
        "",
        " tab. (enter zero to show all on one page)",
        "タブの1ページあたりに表示するユーザータグの数。",
        "Provide help with the use of search.",
        "検索を手助けします。",
        "Search the current subreddit by default when using the search box, instead of all of reddit.",
        "検索する時にreddit全体ではなく現在のサブレディット内を検索対象にする。",
        "Allow you to choose sorting and time range on the search form of the side panel.",
        "サイドパネルで検索する時にソートと時間による絞り込みを可能にする。",
        "When on a user profile, offer to search user's post from the subreddit or multireddit we come from.",
        "ユーザープロフィールにいるとき、サブレディットかマルチレディットからユーザーの投稿を検索する。",
        "Add a submit button to the search field.",
        "検索フィールドに送信ボタンを追加する。",
        "Add a button to hide search options while searching.",
        "検索中に検索条件を隠すボタンを追加する。",
        "Automatically hide search options and suggestions on the search page.",
        "検索ページから検索オプションとサジェストを自動的に隠す。",
        "When clicking on a post's flair, search its subreddit for that flair. ",
        "投稿のフレアーをクリックしたとき、そのフレアーでサブレディット内を検索する。",
        "May not work in some subreddits that hide the actual flair and add pseudo-flair with CSS (only workaround is to disable subreddit style).",
        "サブレディットによっては上手く動かない場合もあります。",
        "Adds an [l+c] link that opens a link and the comments page in new tabs for you in one click.",
        "リンクとコメントを同時に開く[l+c]リンクを表示します。",
        " open comments then link ",
        "コメントを開いてからリンクを開きます。",
        " open link then comments ",
        "リンクを開いてからコメントを開きます。",
        "What order to open the link/comments in.",
        "　　リンクとコメントを開く順番。",
        "Hide the [l=c] when the link is the same as the comments page",
        "リンクとコメントが同じページである場合の[l=c]リンクを表示しません。",
        "Open the [l+c] link in background tabs",
        "[l+c]リンクをバックグラウンドのタブで開く。",
        "Provides a number of style tweaks to the Reddit interface. Also allow you to disable specific subreddit style (the ",
        "いくつかのRedditのスタイル調整機能を提供します。また、特定のサブレディットスタイルを無効にできます。",
        " must be on).",
        "をonにしてください。",
        "Moves the username navbar to the top (great on netbooks!)",
        "ユーザーバーをトップに移動する。",
        "Highlights comment boxes for easier reading / placefinding in large threads.",
        "読みやすくするためにコメントボックスを強調する。",
        "Round corners of comment boxes",
        "コメントボックスの角を丸くする。",
        "Highlight comment box hierarchy on hover (turn off for faster performance)",
        "マウスオーバーしたコメントボックスを強調する。（offにすると処理速度が向上します）",
        "Indent comments by [x] pixels (only enter the number, no 'px')",
        "ピクセル分インデントする。（単位は不要：数字だけを入力してください）",
        "Show comment continuity lines",
        "コメントボックスの左側に点線を表示する。",
        "Discourage CSS3 animations. (This will apply to all of reddit, every subreddit, and RES functionality. However, subreddits might still have some animations.)",
        "CSS3のアニメーションをしない。（これはreddit全体やRESの機能に影響しますが、サブレディットでは効かないかもしれません）",
        "Reddit makes it so no links on comment pages appear as \"visited\" - including user profiles. This option undoes that.",
        "コメントページまたはユーザープロフィールにあるリンクが既読の時に色が変わるようにする。（サブレディットのCSSによってはこの機能が効きません）",
        "Bring back video and text expando buttons for users with compressed link display",
        "compressed link display（redditの設定）がonの時に、ビデオとテキストの展開ボタンを元に戻す。",
        "Hide vote arrows on threads where you cannot vote (e.g. archived due to age)",
        "投票できないスレッドでは投票の矢印を表示しない。（例：古くなってアーカイブ状態になった書き込みなど）",
        " Never ",
        " なし ",
        " On hover ",
        " マウスオーバー時 ",
        " Always ",
        " 常に ",
        "Choose when full link flair should be shown",
        "いつ全リンクフレアーを表示すべきか選択する。",
        "Make edited timestamps bold (e.g. \"last edited 50 minutes ago\")",
        "編集のタイムスタンプを太字で表示する（\"last edited 50 minutes ago\"などの表示）",
        "Use colorblind friendly styles when possible",
        "色盲者用のスタイルが利用できるなら使う。",
        "Add an icon in the omnibar (where the page adress is written) to disable/enable current subreddit style.",
        "ブラウザのアドレスバーにサブレディットスタイルをon/offできるアイコンを追加する。",
        "Scroll the standard subreddit dropdown (useful for pinned header and disabled Subreddit Manager)",
        "基本的なサブレディットドロップダウンをスクロールする。",//（ヘッダを固定していてサブレディット管理が無効な場合に便利、とありますが変化が不明）
        "Draws a line to separate top-level comments for easier distinction.",
        "トップレベルのコメントに線を引いて区別しやすくする。",
        "Specify the color to separate top-level comments",
        "区切り線の色を設定する",
        "Specify how thick (in pixels) of a bar is used to separate top-level comments",
        "線の太さをピクセル単位で指定する",
        "Makes the left sidebar (with multireddits) float as you scroll down so you can always see it.",
        "左側のサイドバーを固定し、スクロールで移動しないようにする。",
        "Adds a hover tooltip to subreddits",
        "サブレディットにマウスオーバーした時にツールチップを表示する。",
        "Delay, in milliseconds, before hover tooltip loads. Default is 800.",
        "ミリ秒　マウスオーバー時に情報を読み込むまでの待ち時間。（デフォルトは800）",
        "Delay, in milliseconds, before hover tooltip fades away. Default is 200.",
        "ミリ秒　マウスカーソルが離れてからツールチップが消えるまでの待ち時間。（デフォルトは200）",
        "Show date (subreddit created...) in US format (i.e. 08-31-2010)",
        "subreddit created...の日時表示をUSフォーマットにする。（月-日-年の順）",
        "Allows you to customize the top bar with your own subreddit shortcuts, including dropdown menus of multi-reddits and more.",
        "トップバーをカスタマイズ可能にして、ショートカットやマルチレディットのドロップダウンを登録できるようにする。",
        "Add +shortcut button in subreddit sidebar for easy addition of shortcuts.",
        "ショートカットを簡単登録できるように、サブレディットのサイドバーに [+shortcut] ボタンを追加する。",
        "For multi-subreddit shortcuts like a+b+c/x, show a dropdown like a/x, b/x, c/x",
        "マルチレディットショートカットの解釈方法を変更する。（例：onの場合、a/x+b/yはa/x/y, b/yと解釈され、offの場合はa/x, b/yと解釈される）",
        "Show \"edit\" and \"delete\" buttons in dropdown menu on subreddit shortcut bar",
        "トップバー（サブレディットのショートカット）のドロップダウンメニューに\"edit\"と\"delete\"ボタンを表示する。",
        "How long (in milliseconds) to wait after moving your mouse over a shortcut to show its dropdown. (This particularly applies for shortcuts to multi-subreddits like sub1+sub2+sub3.)",
        "ミリ秒　ショートカットにマウスオーバーしてからドロップダウンが表示されるまでの待ち時間。（ショートカットにマルチレディットが登録されている場合）",
        "How long (in milliseconds) to wait after moving your mouse over a shortcut to show its dropdown edit buttons. (This particularly applies to just the edit/delete button dropdown.)",
        "ミリ秒　ショートカットにマウスオーバーしてから編集/削除のドロップダウンが表示されるまでの待ち時間。（ショートカットに単一のサブレディットが登録されている場合）",
        "Show \"EDIT\" button in subreddit manager",
        "トップバーに\"EDIT\"を表示する",
        "Show last update information on the front page (work only if you have at least 50/100 subscription, see ",
        "フロントページで最新更新情報を表示する。（通常アカウントでは50以上、goldアカウントでは100以上のサブレディットを購読している場合のみ効果があります。詳しくは",
        " for more info).",
        "）",
        "Include additional functionality to Reddit Markdown tables (only sorting at the moment).",
        "Redditマークダウンで記述した表に機能を追加する（今のところソート機能しかありません）",
        "Enable column sorting.",
        "カラムのソートを有効にする。",
        "Format or show additional information about votes on posts and comments.",
        "投稿とコメントへの投票について追加情報を表示する。",
        "Calculate a post's score from its points and \"liked\" percentage.",
        "投稿のスコアとupvoteの割合からupvote数とdownvote数を計算して表示する。",
        "Calculate the total number of votes.",
        "投票数を計算して表示する。",
        "Bolden post and comment scores, making them easier to find.",
        "投稿とコメントのスコアを太字にして見つけやすくする。",
        " No coloration ",
        " 色を付けない ",
        " Automatic coloration ",
        " 自動で色を付ける ",
        " User-defined coloration ",
        " ユーザー定義の色付け ",
        "Add color to a link's score depending on its value.",
        "　リンクのスコアの値に応じて色を付ける。",
        "				This does not work with reddit's \"compressed link display\" preference.",
        "　この機能はredditの設定で\"compressed link display\"が有効だと機能しません。",
        "Choose a color for colorLinkScore with a threshold of your choice.",
        "閾値と色を設定してください。",
        "score",
        "スコア",
        "color",
        "色",
        " Reddit Classic ",
        " レディットの旧スタイル ",
        "Add color to a comment's score depending on its value.",
        "　コメントのスコアの値に応じて色を付ける。",
        "Add color to the \"controversial\" comment indicator.",
        "論争中のコメントに色を付ける。",
        "Select a color for the \"controversial\" comment indicator.",
        "論争中のコメントを示す色。",
        "Highlights certain users in comment threads: OP, Admin, Friends, Mod - contributed by MrDerk",
        "コメントスレッドの中でOP、管理者、フレンド、モデレーターなどを強調表示する。MrDerk氏の貢献による。（CSSで強制名無し表示を行っているサブレディットでは強調表示が効きません。）",
        "Highlight OP's comments",
        "OP（サブミッションを投稿した人）のコメントを強調表示する。",
        "Color to use to highlight OP. Defaults to original text color",
        "OPを強調するための色。",
        "Color used to highlight OP on hover.",
        "マウスオーバー時にOPを強調するための色。",
        "Highlight Admin's comments",
        "管理者のコメントを強調表示する。",
        "Color to use to highlight Admins. Defaults to original text color",
        "管理者を強調するための色。",
        "Color used to highlight Admins on hover.",
        "マウスオーバー時に管理者を強調するための色。",
        "Highlight Friends' comments",
        "フレンドのコメントを強調表示する。",
        "Color to use to highlight Friends. Defaults to original text color",
        "フレンドを強調するための色。",
        "Color used to highlight Friends on hover.",
        "マウスオーバー時にフレンドを強調するための色。",
        "Highlight Mod's comments",
        "モデレーターのコメントを強調表示する。",
        "Color to use to highlight Mods. Defaults to original text color",
        "モデレーターを強調するための色。",
        "Color used to highlight Mods on hover. Defaults to gray.",
        "マウスオーバー時にモデレーターを強調するための色。",
        "Highlight the person who has the first comment in a tree, within that tree",
        "コメントツリーの中で最初のコメントをした人を強調表示する。（同ツリー中で2回以上コメントしていないと強調されない）",
        "Don't highlight the \"first commenter\" on the first comment in a tree",
        "コメントツリーの中で最初のコメントをした人を強調表示するが、最初のコメントは強調しない。",
        "Color to use to highlight the first-commenter. Defaults to original text color",
        "コメントツリーの中で最初のコメントをした人を強調するための色。",
        "Color used to highlight the first-commenter on hover.",
        "マウスオーバー時にコメントツリーの中で最初のコメントをした人を強調するための色。",
        "Color for highlighted text.",
        "強調されたテキストの色。",
        "Automatically set a special color for each username",
        "各ユーザー名に自動で特別な色を付ける。",
        " Random color, not too bright, consistent for each user; night mode-friendly ",
        " ランダムで明るすぎない色を選ぶ。ナイトモード対応。 ",
        " Simple random color, consistent for each user. (original) ",
        " ランダムな色。 ",
        " All black or, in night mode, all light gray ",
        " 全て黒色（ナイトモードでは灰色） ",
        "Select a method for setting colors for usernames",
        "ユーザー名の色をどのように決めるか選択。",
        "Automatically generate hover color based on normal color.",
        "各項目ごとに通常の色を元にマウスオーバー時の色を生成。",
        "Adds a great deal of customization around users - tagging them, ignoring them, and more. You can manage tagged users on ",
        "ユーザーに関する強力なカスタマイズ（タグ付与、無視、その他）を提供します。",
        "When \"hard ignore\" is off, only post titles and comment text is hidden. When it is on, the entire post is hidden (or for comments, collapsed).",
        "offの場合はサブミッションのタイトルとコメントが隠されますが、「show anyway?（それでも表示する）」リンクをクリックすれば見ることができます。onにすると無視しているユーザーが投稿したサブミッションは完全に見えなくなり、コメントは非表示にしたうえで折り畳まれます。",
        "Color users based on cumulative upvotes / downvotes",
        "upvoteとdownvoteの累積値をもとにユーザーに色を付ける。",
        "By default, store a link to the link/comment you tagged a user on",
        "onの場合、ユーザーにタグを付けるときLink欄に初期値を設定する。offであればLink欄は空欄となる。（Linkを設定した場合はユーザー情報ポップアップからアクセスできる）",
        "By default, store a link to the comments when tagging a user in a link post. Otherwise, the link (that the post refers to) will be used.",
        "onの場合、Link欄の初期値をタグを付けようとしているユーザーのコメントへのURLにする。offの場合、対象がサブミッションの投稿者であれば初期値をソースへのURLにする。",
        "Show information on user (karma, how long they've been a redditor) on hover.",
        "ユーザー名にマウスオーバーした時に情報（カルマ、ID登録からの経過日数）を表示する。",
        "Open the quick message dialog when clicking on the \"send message\" button in hover info, instead of going straight to reddit's message page.",
        "ユーザー情報ポップアップの\"send message\"ボタンを押した時にredditのメッセージページではなくクイックメッセージ入力ボックスを開く。",
        "When clicking the \"give gold\" button on the user hover info on a comment, give gold to the comment.",
        "コメントのユーザー情報ポップアップでgivegoldをクリックしたとき、ユーザーではなくそのコメントに対してgoldを送る。",
        "Show \"highlight\" button in user hover info, for distinguishing posts/comments from particular users.",
        "ユーザー情報ポップアップに\"highlight\"ボタンを表示する。",
        "Color used to highlight a selected user, when \"highlighted\" from hover info.",
        "ユーザー情報ポップアップの\"highlight\"ボタンを押した場合にそのユーザーを強調するための色。",
        "Color used to highlight a selected user on hover.",
        "上記の色で強調されたユーザー名にマウスオーバーした時の色。",
        "Show date (redditor since...) in US format (i.e. 08-31-2010)",
        "ID登録日をUSフォーマット（月-日-年）で表示する",
        "Show the number (i.e. [+6]) rather than [vw]",
        "onの場合はタグの後ろにVote Weightの値（タグを付けるときに設定可能で0の場合は非表示）を表示する。offの場合は[vw]と表示する。",
        "Show the vote weight tooltip on hover (i.e. \"your votes for...\")",
        "タグの後ろに表示されるvote weightにマウスオーバーした時ツールチップで表示する。",
        
        "ctrl-up arrow",
        "ctrl + ↑",
        "ctrl-down arrow",
        "ctrl + ↓",
        "ctrl-left arrow",
        "ctrl + ←",
        "ctrl-right arrow",
        "ctrl + →",
        "shift-up arrow",
        "shift + ↑",
        "shift-down arrow",
        "shift + ↓",
        "Open first link within comment.",
        "[1]番目のリンクを開く。"
    ]);
}

function TranslateSettings(){
    if(translated) return;
    
    TranslateTab("Menu-Accounts", "アカウント", [
		"module-accountSwitcher",
        "アカウント切り替え機能",
		"module-showKarma",
        "コメントカルマ表示",
		"module-userbarHider",
        "ユーザーバーの折り畳み",
		"module-usernameHider",
        "ユーザー名(ID)を隠す"
	]);
	TranslateTab("Menu-Comments", "コメント", [
		"module-commentHidePersistor",
        "コメント非表示の保持", 
        "module-commentNavigator",
        "コメントナビゲーター", 
        "module-commentTools",
        "コメントツール", 
        "module-context", 
        "コンテキスト", 
        "module-hideChildComments",
        "子コメントを隠す", 
        "module-commentPreview",
        "コメントのプレビュー",
        "module-newCommentCount",
        "新着コメント数カウント", 
        "module-noParticipation",
        "不参加",
        "module-saveComments",
        "コメントを保存",
        "module-showParent",
        "マウスオーバーで親を表示",
        "module-sortCommentsTemporarily",
        "一時的なコメント並び替え",
        "module-sourceSnudown",
        "書き込みソース表示"
    ]);
	TranslateTab("Menu-Filters", "フィルタ", [
        "module-filteReddit",
        "フィルター",
        "module-spamButton",
        "スパム報告ボタン",
        "module-subRedditTagger",
        "サブレディットタグ"
	]);
	TranslateTab("Menu-UI", "UI", [
        "module-betteReddit",
        "UI向上",
        "module-showImages",
        "インラインイメージビューア",
        "module-keyboardNav",
        "キーボード操作",
        "module-localDate",
        "ローカル日時",
        "module-logoLink",
        "ロゴリンク",
        "module-neverEndingReddit",
        "終わらないReddit",
        "module-nightMode",
        "ナイトモード",
        "module-quickMessage",
        "クイックメッセージ",
        "module-dashboard",
        "RESダッシュボード",
        "module-searchHelper",
        "検索補助",
        "module-singleClick",
        "シングルクリック",
        "module-styleTweaks",
        "スタイル調整",
        "module-subredditInfo",
        "サブレディット情報",
        "module-subredditManager",
        "サブレディット管理",
        "module-tableTools",
        "表ツール",
        "module-voteEnhancements",
        "投票機能の強化"
    ]);
	TranslateTab("Menu-Users", "ユーザー", [
        "module-userHighlight",
        "ユーザー強調表示",
        "module-userTagger",
        "ユーザータグ"
	]);
/*
    TranslateTab("Menu-About RES", "RESについて", [
        "module-contribute",
        "寄付と貢献",
        "module-about",
        "RESについて",
        "module-commandLine",
        "RESコマンドライン",
        "module-notifications",
        "RES通知",
        "module-hover",
        "RESポップアップ",
        "module-RESTips",
        "RESの便利な使い方",
        "module-submitIssue",
        "問題の報告",
        "module-troubleshooter",
        "トラブルシューター",
        "module-search",
        "RESの設定を検索"
	]);
*/    
    var e = document.getElementsByTagName("h1");
    for(var i in e){
        if(e[i].innerHTML == "reddit enhancement suite"){
            e[i].innerHTML = e[i].innerHTML + "<br>(with nihongo-de-ok)";
        }
    }

    E("RESClose").addEventListener("click", start, false);
    
    var id1 = GetActiveTab();
    var id2 = GetActiveList();

    if(E(id1)){
        E(id1).click();
        if(E(id2)){
            E(id2).click();
        }
    }
    
    translated = true;
}

function TranslateKeyhelp(){
    var e = E("keyHelp");
    if(e.getAttribute("translated_ja") === "true") return;
    TranslateRightPane(e);
    e.setAttribute("translated_ja", "true");
    setTimeout(start, 500);
}

function start(){
	if(E("RESClose")){
		setTimeout(TranslateSettings, 500);
	}
    else if(E("keyHelp")){
		setTimeout(TranslateKeyhelp, 500);
    }
	else{
		setTimeout(start, 500);
	}
}

init();
start();
